/* soapClient.cpp
   Generated by gSOAP 2.7.9l from sentido_da_vida.wsdl.hpp
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.7.9l 2011-05-11 17:19:22 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__SentidoDaVida(struct soap *soap, const char *soap_endpoint, const char *soap_action, double &result)
{	struct ns__SentidoDaVida soap_tmp_ns__SentidoDaVida;
	struct ns__SentidoDaVidaResponse *soap_tmp_ns__SentidoDaVidaResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:50000/ws_test";
	soap->encodingStyle = "";
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns__SentidoDaVida(soap, &soap_tmp_ns__SentidoDaVida);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__SentidoDaVida(soap, &soap_tmp_ns__SentidoDaVida, "ns:SentidoDaVida", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__SentidoDaVida(soap, &soap_tmp_ns__SentidoDaVida, "ns:SentidoDaVida", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_double(soap, &result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns__SentidoDaVidaResponse = soap_get_ns__SentidoDaVidaResponse(soap, NULL, "ns:SentidoDaVidaResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	result = soap_tmp_ns__SentidoDaVidaResponse->result;
	return soap_closesock(soap);
}

/* End of soapClient.cpp */
